# Generated by Django 5.2.4 on 2025-07-21 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('proveedor', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('iva_porcentaje', models.IntegerField(choices=[(0, '0%'), (21, '21%')], default=21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('factura', models.FileField(blank=True, help_text='Adjuntar factura en PDF', null=True, upload_to='facturas/%Y/%m/')),
                ('trimestre', models.IntegerField(choices=[(1, 'Q1 - Primer Trimestre'), (2, 'Q2 - Segundo Trimestre'), (3, 'Q3 - Tercer Trimestre'), (4, 'Q4 - Cuarto Trimestre')])),
                ('año', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('iva_porcentaje', models.IntegerField(choices=[(0, '0%'), (21, '21%')], default=21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('irpf_porcentaje', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('trimestre', models.IntegerField(choices=[(1, 'Q1 - Primer Trimestre'), (2, 'Q2 - Segundo Trimestre'), (3, 'Q3 - Tercer Trimestre'), (4, 'Q4 - Cuarto Trimestre')])),
                ('año', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ResumenTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, 'Q1 - Primer Trimestre'), (2, 'Q2 - Segundo Trimestre'), (3, 'Q3 - Tercer Trimestre'), (4, 'Q4 - Cuarto Trimestre')])),
                ('año', models.IntegerField(default=2025)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficio_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_repercutido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_soportado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irpf_retenido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Resumen Trimestral',
                'verbose_name_plural': 'Resúmenes Trimestrales',
                'ordering': ['-año', '-trimestre'],
                'unique_together': {('trimestre', 'año')},
            },
        ),
    ]
