# Generated by Django 5.2.4 on 2025-07-21 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAutonomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fiscal', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=9, unique=True)),
                ('direccion', models.TextField()),
                ('codigo_postal', models.CharField(max_length=5)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('tipo_irpf_default', models.IntegerField(default=7, help_text='% IRPF por defecto')),
                ('regimen_iva', models.CharField(choices=[('general', 'Régimen General'), ('simplificado', 'Régimen Simplificado'), ('recargo', 'Recargo de Equivalencia')], default='general', max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de Autónomo',
                'verbose_name_plural': 'Perfiles de Autónomos',
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['usuario', '-fecha'], name='accounts_ga_usuario_b8a053_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['usuario', 'trimestre', 'año'], name='accounts_ga_usuario_d1eb14_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['usuario', '-fecha'], name='accounts_in_usuario_aeba56_idx'),
        ),
        migrations.AddIndex(
            model_name='ingreso',
            index=models.Index(fields=['usuario', 'trimestre', 'año'], name='accounts_in_usuario_5d5092_idx'),
        ),
        migrations.AddField(
            model_name='perfilautonomo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
